Update helm-test.yml

diff --git a/.github/workflows/helm-test.yml b/.github/workflows/helm-test.yml
--- a/.github/workflows/helm-test.yml
+++ b/.github/workflows/helm-test.yml
@@ -49,9 +49,9 @@ jobs:
 #        if: steps.list-changed.outputs.changed == 'true'
         run: ct install --target-branch ${{ github.event.repository.default_branch }}
         
-      - name: TESTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
-#        if: steps.list-changed.outputs.changed == 'true'
-        run: |
-          kubectl exec deploy/golden-devops-helm-release --namespace=staging-namespace -- curl --fail localhost || echo "nie1"
-          helm test golden-devops-helm-release || echo "Testing of Helm golden-devops-helm-release failed!"
-          kubectl logs golden-devops-helm-release-connection-test --namespace=staging-namespace
+#       - name: TESTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
+# #        if: steps.list-changed.outputs.changed == 'true'
+#         run: |
+#           kubectl exec deploy/golden-devops-helm-release --namespace=staging-namespace -- curl --fail localhost || echo "nie1"
+#           helm test golden-devops-helm-release || echo "Testing of Helm golden-devops-helm-release failed!"
+#           kubectl logs golden-devops-helm-release-connection-test --namespace=staging-namespace
